WITH stg_hvfhv_trips AS (
     SELECT hvfhs_license_num, 
            dispatching_base_num, 
            originating_base_num, 
            request_datetime, 
            on_scene_datetime, 
            pickup_datetime, 
            dropoff_datetime, 
            pulocationid AS pu_location_id, 
            dolocationid AS do_location_id, 
            trip_miles, 
            trip_time, 
            base_passenger_fare AS fare_amount, 
            tolls AS tolls_amount, 
            bcf, 
            sales_tax, 
            congestion_surcharge, 
            airport_fee, 
            tips AS tip_amount, 
            driver_pay, 
            shared_request_flag, 
            shared_match_flag, 
            access_a_ride_flag, 
            wav_request_flag, 
            wav_match_flag, 
            cbd_congestion_fee, 
            trip_duration_minutes, 
            source_file, 
            ingestion_timestamp, 
            pickup_date,
            'hvfhv' AS trip_type
            FROM {{source('raw','raw_hvfhv_trips')}}
)
SELECT * FROM stg_hvfhv_trips